language: ruby
rvm:
- 2.1
# Assume bundler is being used, install step will run `bundle install`.
script: ./scripts/cibuild

# branch whitelist
branches:
  only:
  - master     # test the master

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer